name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_python-create-version-branch.yml@19ed6d81f20f621a2ea4ef6318d9fe5c0187fbb8
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Ruff",           "directory": ".github/ci/ruff"},
          {"name": "mypy",           "directory": ".github/ci/mypy"},
          {"name": "Bandit",         "directory": ".github/ci/bandit"},
          {"name": "import-linter",  "directory": ".github/ci/importlinter"},
          {"name": "pytest",         "directory": ".github/ci/pytest"}
        ]
