name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: valkyrjaio/.github/.github/workflows/_python-update-dependencies.yml@d8c49368481b9270bc9e089b61731dc9b9561be8
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Root Packages",  "directory": "."},
          {"name": "Ruff",           "directory": ".github/ci/ruff"},
          {"name": "mypy",           "directory": ".github/ci/mypy"},
          {"name": "Bandit",         "directory": ".github/ci/bandit"},
          {"name": "import-linter",  "directory": ".github/ci/importlinter"},
          {"name": "pytest",         "directory": ".github/ci/pytest"}
        ]
