name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: valkyrjaio/.github/.github/workflows/_update-python-dependencies.yml@983eb086a57533c52b7ce86a29b2d537aad838ed
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Root Packages",  "directory": "."},
          {"name": "Ruff",           "directory": ".github/ci/ruff"},
          {"name": "mypy",           "directory": ".github/ci/mypy"},
          {"name": "Bandit",         "directory": ".github/ci/bandit"},
          {"name": "import-linter",  "directory": ".github/ci/importlinter"},
          {"name": "pytest",         "directory": ".github/ci/pytest"}
        ]
